### ISSUE TITLE
Bootstrap 3.3.2 released

### ISSUE THREAD

**Issue by pfafman** [MeteorPackaging/bootstrap#1]
[Bootstrap 3.3.2](http://blog.getbootstrap.com) was released.

Also it is not obvious in the repo where the meteor package.js file is. 
```
  grunt/meteor/package.js
```

**Comment by dandv** [comment]
Thanks for the heads up. Updated https://atmospherejs.com/twbs/bootstrap -

```sh
git clone git@github.com:MeteorPackaging/bootstrap.git
git remote add upstream git@github.com:twbs/bootstrap.git
git fetch upstream
git merge upstream/master
npm install
grunt meteor-test
grunt meteor-publish
```

As for the files being hidden in `grunt`, that's [what the @twbs guys wanted](https://github.com/twbs/bootstrap/pull/15376#issuecomment-67108559).

**Comment by splendido** [comment]
It's autopublish.meteor.com time ;-)

**Comment by dandv** [comment]
From now on, yep! The README was updated with the new `documentation` option for `package.describe`, and there was a conflict in `package.json`.

**Comment by splendido** [comment]
:+1:

**Comment by dandv** [comment]
Hey @splendido, should we delete this repo now that you've managed to get package.js in the official twbs repo?
