### ISSUE TITLE
Fate of this repo

### ISSUE THREAD

**Issue by dandv** [MeteorPackaging/bootstrap#2]
Now that @splendido has gotten [package.js into the official twbs repo](https://github.com/twbs/bootstrap/blob/master/package.js), what should we do with this repo?

Only two things I see potentially useful from https://github.com/MeteorPackaging/bootstrap/tree/meteor-integration/grunt/meteor

* package-noglyphs
* the test.js

**Comment by splendido** [comment]
I'd say we can delete this repo and create a new one to publish the *no-glyphs* version.

I think I'm going to merry [the sister repo approach](https://github.com/MeteorPackaging/autopublish-test-sister) from now on probably adding a `autopublish.json` file to ease the addition of these kind of repositories to the autopublish subscriptions (see also https://github.com/MeteorPackaging/discussions/issues/16)

**Comment by splendido** [comment]
can we delete this one?

**Comment by dandv** [comment]
I'll port the test files to https://github.com/MeteorPackaging/bootswatch so we can delete this one.
